Work around multiple definitions issue
Fixes the error:
"The unique option `programs.password-store.package' is defined
multiple times"
when building home configuration on macOS